---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-dbcreds
  namespace: default
spec:
  encryptedData:
    password: AgChzwBA9j4rdsUkrFw6sK4Fez+TVsuL6It+ZhNfJ/Ojy5Yb5GATv0CVs3aVjaSNvjGP6kOIy+CxhALmvLO84vYRSmi+MENCcvSajgbH36xSWslmOKBNbW4nqmiWRRMPubZMf9WO43RbvntjDh84kSCum7GXcB6lZdn3CNNEjkcXdg0si9x/VM1POi/afbeRgpT99X2rvHC5QG1eAMnOToQTIaxXRijPkK/BWOOvE2zO6XGivmcnMHr4/jGo4Hnf7GhqW0kB921mIBBhS/aXfLwgWFMX0ZD1JyzACtd5Q4GLhYRXQfMTTJHVAWlHNCvERsiQd1agfUF+OJRIfpbsmgqZ+v89Hcwh7qlP4kzimhVxN02v68wEV/Ka62QBMoAqw5T2Yjkku+dxTccoP6bHkr98Y5IqVRVNFKU7m7q96cUnpb+kt91MHe9g1x44vmSMMqCYVwersVFNz9pS3nleXvo0L4am8XcVT6T5yrdBUlCPeEOoi/UuFvJT3TwCho9NoolZBHbGVBlRQBy0HNI9VPR3PCczCbt2cmWK0eAB52KvvCr2l9ApjlS2IgyFLUbN97Eb7mfcbPxiJER8wXiP4m1T4iQNxvIwiHnyJdwPkIF+msTdcx1k7q09o/U6ukcllz8vN4FtiKnMZk+R2mfwWuvrc4wgR88X7mP4EDKvalwP23YlUYUxGOSWl5LQ3cCAR1vbt7xjAE/h6bmT07t/VLpTbQ==
    username: AgAGv/KMQawM/Sp8/gXaMSVogkxE9GN6xRVIKqyqIADZb1gYtmejwu1L25EZ/0DgSE7HW4p/7d9bTI0rHDpNCW8kTJfGrS94YLMAw0giMGBNTd4HSTrFmnPJ/e6AT2moWAMkuSx8zb6XQkx/V6VBS4k1WzuNCuY8AmwF9klvr+ibSlRi2LzcvOI3mwtAqabTjhDQry6deK0fDNskJWWFyxOvqxrTa75fuyIfC2LPXrItSx/wchAYkPyLLgl+ejjm7wKB3v63zdplPaiuT+XLn9H8jxspgW4x95IERHPq1KIvMFzRWgOGM9Frgd4tYHmDXy3rgmRsnPVnYKM7+Kc42dTaXREoZWpDLv+qp36mQETwIjviTcEv+yQpYathQIWempCt7ikWnj/XAEgYU8PPawI+mT09ESCVensfSa08pXnl0wPiI27BvzyB5Po9cz4dctdutdJIUhZYTUo5ge5E3DlaoTRk2w7PhQlXNeJ7ZCuenSnIKsy94zIinuyFNxG8n64I6Z3QhDaMPUZpVTeizMKwFFeUYIfhMeplGBcKnqNe2DpL42KMnUOd9NZTexC08eus9FdHJDsN1gCjJfLzcX4k0tv/DFmVH53avy8tRiHC0HRCW/NOPne1LAbDhq21O4BkkowB6KcIkPFHlxxOH1Ni7CEKxznUGFkclpRsoCCN4gEhQWLsQfGB2wD8LvzEYpTvAkAJ6w==
  template:
    metadata:
      creationTimestamp: null
      name: my-dbcreds
      namespace: default
